#!/bin/sh
# dFlow — community fork — one-command installer
#
#   curl -fsSL https://raw.githubusercontent.com/Dvorinka/dflow/main/install.sh | bash
#
# Installs the app + MongoDB + Redis into ./dflow and starts it on :3000.
# Optional extras live behind compose profiles:
#   docker compose --env-file .env -p dflow --profile proxy up -d       # traefik + TLS
#   docker compose --env-file .env -p dflow --profile monitoring up -d  # beszel
#
# Env overrides: DFLOW_DIR, APP_PORT, DFLOW_IMAGE, WILD_CARD_DOMAIN,
# TRAEFIK_EMAIL, MONGO_INITDB_ROOT_PASSWORD, PAYLOAD_SECRET.

set -e

DFLOW_DIR="${DFLOW_DIR:-dflow}"
APP_PORT="${APP_PORT:-3000}"
COMPOSE_URL="https://raw.githubusercontent.com/Dvorinka/dflow/main/docker-compose.yml"

bold=$(printf '\033[1m'); dim=$(printf '\033[90m'); reset=$(printf '\033[0m')

say()  { printf '%s%s%s\n' "$bold" "$*" "$reset"; }
note() { printf '%s%s%s\n' "$dim" "$*" "$reset"; }
die()  { printf 'error: %s\n' "$*" >&2; exit 1; }

# --- prerequisites -------------------------------------------------------

command -v docker >/dev/null 2>&1 || die "docker not found. Install it: curl -fsSL https://get.docker.com | sh"
docker compose version >/dev/null 2>&1 || die "docker compose plugin not found — install Docker ≥20.10 or the compose plugin"
command -v curl >/dev/null 2>&1 || die "curl not found"

# --- workspace -----------------------------------------------------------

mkdir -p "$DFLOW_DIR" && cd "$DFLOW_DIR"

if [ ! -f docker-compose.yml ]; then
  curl -fsSL "$COMPOSE_URL" -o docker-compose.yml || die "failed to download docker-compose.yml"
  note "downloaded docker-compose.yml"
fi

# The compose file bind-mounts ./scripts into the app container.
# traefik/dynamic/acme.json only matter for --profile proxy but docker
# creates missing bind-mount sources as directories, which breaks traefik.
mkdir -p scripts dynamic
[ -f acme.json ] || (touch acme.json && chmod 600 acme.json)

# --- .env ----------------------------------------------------------------

if [ ! -f .env ]; then
  PAYLOAD_SECRET="${PAYLOAD_SECRET:-$(openssl rand -base64 32 | tr -d '=+/' | cut -c1-32)}"
  MONGO_INITDB_ROOT_PASSWORD="${MONGO_INITDB_ROOT_PASSWORD:-$(openssl rand -base64 24 | tr -d '=+/' | cut -c1-24)}"

  cat <<EOF > .env
# Generated by dflow install.sh — edit freely, then re-run compose.

# core
MONGO_INITDB_ROOT_USERNAME=admin
MONGO_INITDB_ROOT_PASSWORD=$MONGO_INITDB_ROOT_PASSWORD
MONGO_DB_NAME=dflow
PAYLOAD_SECRET=$PAYLOAD_SECRET
NEXT_PUBLIC_WEBSITE_URL=http://localhost:$APP_PORT
APP_PORT=$APP_PORT
AUTH_METHOD=email-password
NEXT_PUBLIC_TELEMETRY_DISABLED=1

# traefik / proxy profile (set these before enabling --profile proxy)
WILD_CARD_DOMAIN=${WILD_CARD_DOMAIN:-}
JWT_TOKEN=$PAYLOAD_SECRET
PROXY_PORT=9999
TRAEFIK_EMAIL=${TRAEFIK_EMAIL:-}
NEXT_PUBLIC_PROXY_DOMAIN_URL=${WILD_CARD_DOMAIN:-}
NEXT_PUBLIC_PROXY_CNAME=

# optional integrations — fill in when needed
TAILSCALE_AUTH_KEY=
TAILSCALE_OAUTH_CLIENT_SECRET=
TAILSCALE_TAILNET=
TAILSCALE_LOGIN_SERVER=
NETBIRD_API_URL=
NETBIRD_API_TOKEN=
NETBIRD_MANAGEMENT_URL=
ZEROTIER_API_URL=
ZEROTIER_API_TOKEN=
ZEROTIER_NETWORK_ID=
RESEND_API_KEY=
RESEND_SENDER_EMAIL=
RESEND_SENDER_NAME=
S3_ENDPOINT=
S3_REGION=
S3_ACCESS_KEY_ID=
S3_SECRET_ACCESS_KEY=
BESZEL_MONITORING_URL=
BESZEL_SUPERUSER_EMAIL=
BESZEL_SUPERUSER_PASSWORD=
BESZEL_HUB_SSHKEY=
NEXT_PUBLIC_BETTER_STACK_SOURCE_TOKEN=
NEXT_PUBLIC_BETTER_STACK_INGESTING_URL=
NEXT_PUBLIC_WEBHOOK_URL=
EOF
  note "wrote .env (random secrets generated)"
fi

# --- launch --------------------------------------------------------------

say "Starting dFlow (app + mongodb + redis)…"
docker compose --env-file .env -p dflow pull payload-app mongodb redis
docker compose --env-file .env -p dflow up -d mongodb redis payload-app

printf '\n'
say "dFlow is starting → http://localhost:$APP_PORT"
note "First boot takes a minute while Payload connects to MongoDB."
note "Optional extras:"
note "  --profile proxy       traefik + TLS (needs WILD_CARD_DOMAIN + DNS)"
note "  --profile monitoring  beszel + agent"
note "Logs: docker compose -p dflow logs -f payload-app"
