import configPromise from '@payload-config'
import { Job } from 'bullmq'
import { randomUUID } from 'crypto'
import { mkdtempSync, rmSync } from 'fs'
import { NodeSSH } from 'node-ssh'
import { tmpdir } from 'os'
import { join } from 'path'
import { getPayload } from 'payload'

import { pluginList } from '@/components/plugins'
import { getQueue, getWorker } from '@/lib/bullmq'
import { dokku } from '@/lib/dokku'
import { jobOptions, pub, queueConnection } from '@/lib/redis'
import { sendActionEvent, sendEvent } from '@/lib/sendEvent'
import { SSHType, dynamicSSH } from '@/lib/ssh'
import { DatabaseType, parseDatabaseInfo } from '@/lib/utils'
import { Service } from '@/payload-types'

interface QueueArgs {
  sourceServiceId: Service['id']
  sourceDatabaseName: string
  databaseType: DatabaseType
  imageVersion?: string
  sourceServerId: string
  targetServerId: string
  targetProjectId: string
  targetDatabaseName: string
  targetServiceId: string
  targetDeploymentId: string
  sourceSshDetails: SSHType
  targetSshDetails: SSHType
  tenant: {
    slug: string
  }
  userId: string
}

// Migrates a dokku datastore service from one server to another (#408):
// export on source → sftp hop through this process → dokku create + import
// on target. Credentials are regenerated by the target plugin and written
// to the new service record; dependent apps still need their env vars
// re-linked manually.
export const addDatabaseMigrateQueue = async (data: QueueArgs) => {
  const QUEUE_NAME = `server-${data.targetServerId}-migrate-database`

  const migrateQueue = getQueue({
    name: QUEUE_NAME,
    connection: queueConnection,
  })

  const worker = getWorker<QueueArgs>({
    name: QUEUE_NAME,
    connection: queueConnection,
    processor: async job => {
      const payload = await getPayload({ config: configPromise })
      const {
        sourceServiceId,
        sourceDatabaseName,
        databaseType,
        imageVersion,
        sourceServerId,
        targetServerId,
        targetDatabaseName,
        targetServiceId,
        targetDeploymentId,
        sourceSshDetails,
        targetSshDetails,
        tenant,
      } = job.data

      const channelId = targetDeploymentId
      const dumpFileName = `${sourceDatabaseName}-migrate-${randomUUID()}.dump`
      const remoteDumpPath = `/tmp/${dumpFileName}`
      const localDir = mkdtempSync(join(tmpdir(), 'dflow-migrate-'))
      const localDumpPath = join(localDir, dumpFileName)

      let sourceSsh: NodeSSH | null = null
      let targetSsh: NodeSSH | null = null

      const log = (message: string) =>
        sendEvent({
          pub,
          message,
          serverId: targetServerId,
          serviceId: targetServiceId,
          channelId,
        })

      try {
        await payload.update({
          collection: 'deployments',
          id: targetDeploymentId,
          data: { status: 'building' },
        })
        sendActionEvent({ pub, action: 'refresh', tenantSlug: tenant.slug })

        // 1. Ensure the datastore plugin exists on the target
        targetSsh = await dynamicSSH(targetSshDetails)
        const pluginsResponse = await dokku.plugin.list(targetSsh)
        const installed = pluginsResponse.plugins.some(
          plugin => plugin.name === databaseType && plugin.status,
        )

        if (!installed) {
          const pluginData = pluginList.find(p => p.value === databaseType)
          if (!pluginData?.githubURL) {
            throw new Error(
              `dokku plugin ${databaseType} is not installed on the target server and has no known install source`,
            )
          }

          await log(`Installing missing ${databaseType} plugin on target...`)
          await dokku.plugin.install({
            ssh: targetSsh,
            pluginUrl: pluginData.githubURL,
            pluginName: databaseType,
          })
        }

        // 2. Create the database on the target and persist credentials
        await log(`Creating ${databaseType} database ${targetDatabaseName}...`)
        const createResult = await dokku.database.create(
          targetSsh,
          targetDatabaseName,
          databaseType,
          {
            onStdout: async chunk => log(chunk.toString()),
            onStderr: async chunk => log(chunk.toString()),
          },
          imageVersion ? { imageVersion } : undefined,
        )

        if (createResult.code !== 0) {
          throw new Error(
            `dokku ${databaseType}:create failed: ${createResult.stderr}`,
          )
        }

        const formattedData = parseDatabaseInfo({
          stdout: createResult.stdout,
          dbType: databaseType,
        })

        await payload.update({
          collection: 'services',
          id: targetServiceId,
          data: { databaseDetails: { ...formattedData } },
        })

        // 3. Export on source
        await log(`Exporting ${sourceDatabaseName} on source server...`)
        sourceSsh = await dynamicSSH(sourceSshDetails)
        const exportResult = await dokku.database.internal.export(
          sourceSsh,
          databaseType,
          sourceDatabaseName,
          remoteDumpPath,
          {
            onStdout: async chunk => log(chunk.toString()),
            onStderr: async chunk => log(chunk.toString()),
          },
        )
        if (exportResult.code !== 0) {
          throw new Error(
            `Export failed on source server: ${exportResult.stderr}`,
          )
        }

        // 4. Transfer dump source → local → target
        await log('Transferring dump to target server...')
        await sourceSsh.getFile(localDumpPath, remoteDumpPath)
        await targetSsh.putFile(localDumpPath, remoteDumpPath)

        // 5. Import on target
        await log(`Importing into ${targetDatabaseName}...`)
        const importResult = await dokku.database.internal.import(
          targetSsh,
          databaseType,
          targetDatabaseName,
          remoteDumpPath,
          {
            onStdout: async chunk => log(chunk.toString()),
            onStderr: async chunk => log(chunk.toString()),
          },
        )
        if (importResult.code !== 0) {
          throw new Error(
            `Import failed on target server: ${importResult.stderr}`,
          )
        }

        const logs = await pub.lrange(channelId, 0, -1)
        await payload.update({
          collection: 'deployments',
          id: targetDeploymentId,
          data: { status: 'success', logs },
        })

        await log(
          `Migrated ${sourceDatabaseName} → ${targetDatabaseName}. Re-link dependent services to the new database when ready; the source database is untouched.`,
        )

        const { trackActivity } = await import('@/lib/activityTracker')
        await trackActivity({
          payload,
          userId: job.data.userId,
          eventType: 'database_migrated',
          operation: 'update',
          label: 'Database Migrated',
          status: 'success',
          severity: 'warning',
          category: 'database',
          collectionSlug: 'services',
          documentId: sourceServiceId,
          icon: 'database',
          metadata: {
            databaseType,
            from: { serverId: sourceServerId, name: sourceDatabaseName },
            to: {
              serverId: targetServerId,
              name: targetDatabaseName,
              serviceId: targetServiceId,
            },
          },
        })
      } catch (error) {
        const message = error instanceof Error ? error.message : 'Unknown error'
        await log(`${message}`)

        const logs = await pub.lrange(channelId, 0, -1)
        await payload
          .update({
            collection: 'deployments',
            id: targetDeploymentId,
            data: { status: 'failed', logs },
          })
          .catch(() => {})

        throw new Error(
          `Database migration failed for ${sourceDatabaseName}: ${message}`,
        )
      } finally {
        // Clean up dumps on both servers and locally
        await sourceSsh
          ?.execCommand(`rm -f ${remoteDumpPath}`)
          .catch(() => {})
        await targetSsh
          ?.execCommand(`rm -f ${remoteDumpPath}`)
          .catch(() => {})
        rmSync(localDir, { recursive: true, force: true })

        sendActionEvent({ pub, action: 'refresh', tenantSlug: tenant.slug })
        sourceSsh?.dispose()
        targetSsh?.dispose()
      }
    },
  })

  worker.on('failed', async (job: Job<QueueArgs> | undefined, err) => {
    if (job?.data) {
      sendEvent({
        pub,
        message: err.message,
        serverId: job.data.targetServerId,
        serviceId: job.data.targetServiceId,
        channelId: job.data.targetDeploymentId,
      })
    }
  })

  const id = `migrate-database-${data.databaseType}-${data.targetDatabaseName}:${Date.now()}`
  return await migrateQueue.add(id, data, { ...jobOptions, jobId: id })
}
